import 'package:flutter/material.dart';

import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Frame1(),
        ]),
      ),
    );
  }
}

class Frame1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 897,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 1494,
                  padding: const EdgeInsets.only(bottom: 602),
                  decoration: BoxDecoration(color: Color(0xFFFDF7EB)),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(width: 473, height: 932),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 72,
                child: Container(
                  width: 316,
                  height: 1307,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 5,
                        child: SizedBox(
                          width: 230,
                          height: 110,
                          child: Text(
                            'Welcome,[name].',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 44,
                              fontFamily: 'Istok Web',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 267,
                        top: 0,
                        child: Container(
                          width: 49,
                          height: 49,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Image.asset("assets/location_on.png"),
                        ),
                      ),
                      Positioned(
                        left: 273,
                        top: 49,
                        child: Text(
                          'MIT',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Istok Web',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 2,
                        top: 177,
                        child: Text(
                          'Dining Halls:',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 36,
                            fontFamily: 'Istok Web',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 251,
                        top: 177,
                        child: Container(
                          width: 45,
                          height: 45,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 45,
                                  height: 45,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFF9BB9D),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 7.79,
                                top: 7.79,
                                child: Container(
                                  width: 29.42,
                                  height: 29.42,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: FlutterLogo(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 274,
                        child: Container(
                          width: 139,
                          height: 174,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 145,
                                child: Text(
                                  'Maseeh Hall',
                                  style: TextStyle(
                                    color: Color(0xFF756382),
                                    fontSize: 20,
                                    fontFamily: 'Istok Web',
                                    fontWeight: FontWeight.w700,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Image.asset("assets/maseeh.png")
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 177,
                        top: 274,
                        child: Container(
                          width: 139,
                          height: 174,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 145,
                                child: Text(
                                  'Maseeh Hall',
                                  style: TextStyle(
                                    color: Color(0xFF756382),
                                    fontSize: 20,
                                    fontFamily: 'Istok Web',
                                    fontWeight: FontWeight.w700,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Image.asset("assets/maseeh.png")
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 476,
                        child: Container(
                          width: 139,
                          height: 174,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 145,
                                child: Text(
                                  'Maseeh Hall',
                                  style: TextStyle(
                                    color: Color(0xFF756382),
                                    fontSize: 20,
                                    fontFamily: 'Istok Web',
                                    fontWeight: FontWeight.w700,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Image.asset("assets/maseeh.png")
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 177,
                        top: 476,
                        child: Container(
                          width: 139,
                          height: 174,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 145,
                                child: Text(
                                  'Maseeh Hall',
                                  style: TextStyle(
                                    color: Color(0xFF756382),
                                    fontSize: 20,
                                    fontFamily: 'Istok Web',
                                    fontWeight: FontWeight.w700,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Image.asset("assets/maseeh.png")
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 695,
                        child: Container(
                          width: 139,
                          height: 174,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 145,
                                child: Text(
                                  'Maseeh Hall',
                                  style: TextStyle(
                                    color: Color(0xFF756382),
                                    fontSize: 20,
                                    fontFamily: 'Istok Web',
                                    fontWeight: FontWeight.w700,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Image.asset("assets/maseeh.png")
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 177,
                        top: 695,
                        child: Container(
                          width: 139,
                          height: 174,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 145,
                                child: Text(
                                  'Maseeh Hall',
                                  style: TextStyle(
                                    color: Color(0xFF756382),
                                    fontSize: 20,
                                    fontFamily: 'Istok Web',
                                    fontWeight: FontWeight.w700,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Image.asset("assets/maseeh.png")
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 914,
                        child: Container(
                          width: 139,
                          height: 174,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 145,
                                child: Text(
                                  'Maseeh Hall',
                                  style: TextStyle(
                                    color: Color(0xFF756382),
                                    fontSize: 20,
                                    fontFamily: 'Istok Web',
                                    fontWeight: FontWeight.w700,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Image.asset("assets/maseeh.png")
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 177,
                        top: 914,
                        child: Container(
                          width: 139,
                          height: 174,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 145,
                                child: Text(
                                  'Maseeh Hall',
                                  style: TextStyle(
                                    color: Color(0xFF756382),
                                    fontSize: 20,
                                    fontFamily: 'Istok Web',
                                    fontWeight: FontWeight.w700,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Image.asset("assets/maseeh.png")
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 1133,
                        child: Container(
                          width: 139,
                          height: 174,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 145,
                                child: Text(
                                  'Maseeh Hall',
                                  style: TextStyle(
                                    color: Color(0xFF756382),
                                    fontSize: 20,
                                    fontFamily: 'Istok Web',
                                    fontWeight: FontWeight.w700,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Image.asset("assets/maseeh.png")
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 774,
                child: Container(
                  width: 393,
                  height: 78,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 393,
                          height: 78,
                          decoration: BoxDecoration(color: Color(0xFF756382)),
                        ),
                      ),
                      Positioned(
                        left: 290,
                        top: 13,
                        child: Container(
                          width: 50,
                          height: 50,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: FlutterLogo(),
                        ),
                      ),
                      Positioned(
                        left: 168,
                        top: 11,
                        child: Container(
                          width: 56,
                          height: 56,
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 59,
                        top: 15,
                        child: Container(
                          width: 47,
                          height: 47,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 47,
                                  height: 47,
                                  padding: const EdgeInsets.all(12),
                                  clipBehavior: Clip.antiAlias,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFFDF7EB),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(32),
                                    ),
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 23,
                                        height: 23,
                                        clipBehavior: Clip.antiAlias,
                                        decoration: BoxDecoration(),
                                        child: FlutterLogo(),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 6,
                                top: 5,
                                child: Container(
                                  width: 36,
                                  height: 36,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}